default: &default
  adapter: mysql2
  username: root
  password: root
  pool: 5
  timeout: 5000
  host: localhost

development:
  <<: *default
  database: dinneer_web_development

test:
  <<: *default
  database: dinneer_web
